---
# tasks file for ctf_monitor_server

- name: Add Key
  shell:
    cmd: wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -

- name: Add repository
  shell:
    cmd: echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-7.x.list

- name: Install dependencies and softwares
  apt:
      name:
        - net-tools
        - metricbeat
      state: present
      update_cache: yes

- name: template to /etc/metricbeat/metricbeat.yml
  template:
    src: metricbeat_client.j2
    dest: /etc/metricbeat/metricbeat.yml

- name: Service metricbeat start and enable
  service:
    name: metricbeat
    state: started
    enabled: yes

