---
- hosts: ELK_Server
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - role: elk_server
      tags: ELK_Server

- hosts: ELK_Client
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - role: log_client
      tags: [ ELK_Client ]
    - role: metric_client
      tags: [ ELK_Client ]

