---
- hosts: ELK_Server
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - role: elk_monitor_metric_server
      tags: ELK_Server
    - role: elk_monitor_log_server
      tags: ELK_Server

- hosts: ELK_Client
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - role: elk_monitor_metric_client
      tags: [ ELK_Client ]
    - role: elk_monitor_log_client
      tags: [ ELK_Client ]

