---
# tasks 
- name: copy certs & keys to kibana
  copy:
    src: /tmp/certs
    dest: /etc/kibana/
    remote_src: yes

- name: template to kibana.yml of https
  template:
    src: kibana_server_https.j2
    dest: /etc/kibana/kibana.yml

- name: restart kibana
  service:
    name: kibana
    state: restarted

