---
# tasks file for ctf_monitor_server

- name: template to /etc/rsyslog.d/60-output.conf
  template:
    src: 60-output_server.conf.j2
    dest: /etc/rsyslog.d/60-output.conf

- name: template to /etc/logstash/conf.d/logstash.conf
  template:
    src: logstash_server.conf.j2
    dest: /etc/logstash/conf.d/logstash.conf

- name: Service logstash start
  service:
    name: logstash
    state: started
    enabled: yes

- name: restart rsyslog
  service:
    name: rsyslog
    state: restarted

- name: Service logstash restart
  service:
    name: logstash
    state: restarted

