version: '3'
services:
  app1:
    restart: always
    build: .
    depends_on:
      - mysql1
    links:
      - mysql1:mysql
    container_name: web1_app1
    ports:
    - "22222:80"
  mysql1:
    restart: always
    image: mysql:5.7.16
    container_name: web1_mysql1
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=ctf"
      - "TZ=Asia/Shanghai"
