---
# tasks file for ctf_monitor_server



- name: template to /etc/metricbeat/metricbeat.yml
  template:
    src: metricbeat_client.j2
    dest: /etc/metricbeat/metricbeat.yml

- name: Service metricbeat start and enable
  service:
    name: metricbeat
    state: restarted
    enabled: yes

